/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    GlobalDialog: typeof import('./components/GlobalDialog.vue')['default']
    GlobalLoading: typeof import('./components/GlobalLoading.vue')['default']
    GlobalMessage: typeof import('./components/GlobalMessage.vue')['default']
    GlobalToast: typeof import('./components/GlobalToast.vue')['default']
    PrivacyPopup: typeof import('./components/PrivacyPopup.vue')['default']
    SkeletonPage: typeof import('./components/SkeletonPage.vue')['default']
    StatusBadge: typeof import('./components/StatusBadge.vue')['default']
    WdActionSheet: typeof import('@wot-ui/ui/components/wd-action-sheet/wd-action-sheet.vue')['WdActionSheet']
    WdAvatar: typeof import('@wot-ui/ui/components/wd-avatar/wd-avatar.vue')['WdAvatar']
    WdBacktop: typeof import('@wot-ui/ui/components/wd-backtop/wd-backtop.vue')['WdBacktop']
    WdBadge: typeof import('@wot-ui/ui/components/wd-badge/wd-badge.vue')['WdBadge']
    WdButton: typeof import('@wot-ui/ui/components/wd-button/wd-button.vue')['WdButton']
    WdCell: typeof import('@wot-ui/ui/components/wd-cell/wd-cell.vue')['WdCell']
    WdCellGroup: typeof import('@wot-ui/ui/components/wd-cell-group/wd-cell-group.vue')['WdCellGroup']
    WdCheckbox: typeof import('@wot-ui/ui/components/wd-checkbox/wd-checkbox.vue')['WdCheckbox']
    WdConfigProvider: typeof import('@wot-ui/ui/components/wd-config-provider/wd-config-provider.vue')['WdConfigProvider']
    WdDialog: typeof import('@wot-ui/ui/components/wd-dialog/wd-dialog.vue')['WdDialog']
    WdEmpty: typeof import('@wot-ui/ui/components/wd-empty/wd-empty.vue')['WdEmpty']
    WdForm: typeof import('@wot-ui/ui/components/wd-form/wd-form.vue')['WdForm']
    WdFormItem: typeof import('@wot-ui/ui/components/wd-form-item/wd-form-item.vue')['WdFormItem']
    WdGap: typeof import('@wot-ui/ui/components/wd-gap/wd-gap.vue')['WdGap']
    WdIcon: typeof import('@wot-ui/ui/components/wd-icon/wd-icon.vue')['WdIcon']
    WdInput: typeof import('@wot-ui/ui/components/wd-input/wd-input.vue')['WdInput']
    WdLoading: typeof import('@wot-ui/ui/components/wd-loading/wd-loading.vue')['WdLoading']
    WdNavbar: typeof import('@wot-ui/ui/components/wd-navbar/wd-navbar.vue')['WdNavbar']
    WdNoticeBar: typeof import('@wot-ui/ui/components/wd-notice-bar/wd-notice-bar.vue')['WdNoticeBar']
    WdNotify: typeof import('@wot-ui/ui/components/wd-notify/wd-notify.vue')['WdNotify']
    WdPopup: typeof import('@wot-ui/ui/components/wd-popup/wd-popup.vue')['WdPopup']
    WdSkeleton: typeof import('@wot-ui/ui/components/wd-skeleton/wd-skeleton.vue')['WdSkeleton']
    WdSwitch: typeof import('@wot-ui/ui/components/wd-switch/wd-switch.vue')['WdSwitch']
    WdTabbar: typeof import('@wot-ui/ui/components/wd-tabbar/wd-tabbar.vue')['WdTabbar']
    WdTabbarItem: typeof import('@wot-ui/ui/components/wd-tabbar-item/wd-tabbar-item.vue')['WdTabbarItem']
    WdTag: typeof import('@wot-ui/ui/components/wd-tag/wd-tag.vue')['WdTag']
    WdText: typeof import('@wot-ui/ui/components/wd-text/wd-text.vue')['WdText']
    WdToast: typeof import('@wot-ui/ui/components/wd-toast/wd-toast.vue')['WdToast']
    WdWatermark: typeof import('@wot-ui/ui/components/wd-watermark/wd-watermark.vue')['WdWatermark']
  }
}
