/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

type _LocationUrl =
  "/pages/index/index" |
  "/pages/error/index" |
  "/pages/login/index" |
  "/pages/mine/index" |
  "/pages/login/forget/index" |
  "/pages/login/register/index" |
  "/subPages/about/index" |
  "/subPages/setting/index" |
  "/subPages/module_app/address/form" |
  "/subPages/module_app/address/index" |
  "/subPages/module_app/bank-account/form" |
  "/subPages/module_app/bank-account/index" |
  "/subPages/module_system/account/index" |
  "/subPages/module_system/kyc/index" |
  "/subPages/module_system/notices/index" |
  "/subPages/module_system/profile/index";

interface NavigateToOptions {
  url: _LocationUrl;
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index/index" | "/pages/mine/index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}

declare module "virtual:uni-pages" {
  export type LocationUrl = _LocationUrl;
}
