"""Align the existing KYC Generator metadata with the review workspace.

The KYC Admin page is hand-authored and is intentionally not regenerated by
this revision.  The metadata remains useful for discovery and future tooling,
but no longer describes a generic editable database form.
"""

from datetime import UTC, datetime
from uuid import uuid4

import sqlalchemy as sa
from alembic import op

revision = "11d_kyc_admin_workspace"
down_revision = "11c_app_user_admin"
branch_labels = None
depends_on = None


def _column(
    *,
    comment: str,
    column_type: str,
    python_type: str,
    python_field: str,
    nullable: bool,
    is_pk: bool = False,
    is_increment: bool = False,
    is_unique: bool = False,
    is_list: bool = False,
    is_query: bool = False,
    query_type: str | None = None,
    html_type: str = "input",
    dict_type: str = "",
    sort: int,
    length: str = "",
    default: str = "",
) -> dict[str, object]:
    return {
        "column_comment": comment,
        "column_type": column_type,
        "column_length": length,
        "column_default": default,
        "is_pk": is_pk,
        "is_increment": is_increment,
        "is_nullable": nullable,
        "is_unique": is_unique,
        "python_type": python_type,
        "python_field": python_field,
        "is_insert": False,
        "is_edit": False,
        "is_list": is_list,
        "is_query": is_query,
        "query_type": query_type,
        "html_type": html_type,
        "dict_type": dict_type,
        "sort": sort,
    }


_GENERATOR_COLUMNS = (
    (
        "app_user_id",
        _column(
            comment="用户端用户ID（用户列辅助信息）",
            column_type="INTEGER",
            python_type="int",
            python_field="app_user_id",
            nullable=False,
            is_query=True,
            query_type="EQ",
            sort=1,
        ),
    ),
    (
        "real_name",
        _column(
            comment="真实姓名",
            column_type="VARCHAR(128)",
            length="128",
            python_type="str",
            python_field="real_name",
            nullable=True,
            is_list=True,
            is_query=True,
            query_type="LIKE",
            sort=2,
        ),
    ),
    (
        "id_card_no",
        _column(
            comment="证件号码",
            column_type="VARCHAR(64)",
            length="64",
            python_type="str",
            python_field="id_card_no",
            nullable=False,
            is_list=True,
            is_query=True,
            query_type="LIKE",
            sort=3,
        ),
    ),
    (
        "id_card_front",
        _column(
            comment="证件正面地址",
            column_type="VARCHAR(512)",
            length="512",
            python_type="str",
            python_field="id_card_front",
            nullable=True,
            html_type="imageUpload",
            sort=4,
        ),
    ),
    (
        "id_card_back",
        _column(
            comment="证件反面地址",
            column_type="VARCHAR(512)",
            length="512",
            python_type="str",
            python_field="id_card_back",
            nullable=True,
            html_type="imageUpload",
            sort=5,
        ),
    ),
    (
        "status",
        _column(
            comment="实名状态（复用 app_user_kyc_status）",
            column_type="INTEGER",
            python_type="int",
            python_field="status",
            nullable=False,
            is_list=True,
            is_query=True,
            query_type="EQ",
            html_type="select",
            dict_type="app_user_kyc_status",
            sort=6,
        ),
    ),
    (
        "review_remark",
        _column(
            comment="审核备注",
            column_type="VARCHAR(512)",
            length="512",
            python_type="str",
            python_field="review_remark",
            nullable=True,
            html_type="textarea",
            sort=7,
        ),
    ),
    (
        "reviewed_at",
        _column(
            comment="审核时间",
            column_type="DATETIME",
            python_type="datetime",
            python_field="reviewed_at",
            nullable=True,
            is_list=True,
            html_type="datetime",
            sort=8,
        ),
    ),
    (
        "id",
        _column(
            comment="主键ID",
            column_type="INTEGER",
            python_type="int",
            python_field="id",
            nullable=False,
            is_pk=True,
            is_increment=True,
            sort=9,
        ),
    ),
    (
        "uuid",
        _column(
            comment="UUID全局唯一标识",
            column_type="VARCHAR(64)",
            length="64",
            python_type="str",
            python_field="uuid",
            nullable=False,
            is_unique=True,
            sort=10,
        ),
    ),
    (
        "is_deleted",
        _column(
            comment="是否已删除（技术字段）",
            column_type="TINYINT",
            python_type="bool",
            python_field="is_deleted",
            nullable=False,
            sort=11,
        ),
    ),
    (
        "created_time",
        _column(
            comment="提交时间",
            column_type="DATETIME",
            python_type="datetime",
            python_field="created_time",
            nullable=False,
            is_list=True,
            is_query=True,
            query_type="BETWEEN",
            html_type="datetime",
            sort=12,
        ),
    ),
    (
        "updated_time",
        _column(
            comment="更新时间（技术字段）",
            column_type="DATETIME",
            python_type="datetime",
            python_field="updated_time",
            nullable=False,
            sort=13,
        ),
    ),
    (
        "deleted_time",
        _column(
            comment="删除时间（技术字段）",
            column_type="DATETIME",
            python_type="datetime",
            python_field="deleted_time",
            nullable=True,
            sort=14,
        ),
    ),
)


def _generator_table() -> sa.TableClause:
    return sa.table(
        "gen_table",
        sa.column("id", sa.Integer()),
        sa.column("table_name", sa.String(length=200)),
        sa.column("is_deleted", sa.Boolean()),
    )


def _generator_column_table() -> sa.TableClause:
    return sa.table(
        "gen_table_column",
        sa.column("id", sa.Integer()),
        sa.column("column_name", sa.String(length=200)),
        sa.column("table_id", sa.Integer()),
        sa.column("column_comment", sa.String(length=500)),
        sa.column("column_type", sa.String(length=100)),
        sa.column("column_length", sa.String(length=50)),
        sa.column("column_default", sa.String(length=200)),
        sa.column("is_pk", sa.Boolean()),
        sa.column("is_increment", sa.Boolean()),
        sa.column("is_nullable", sa.Boolean()),
        sa.column("is_unique", sa.Boolean()),
        sa.column("python_type", sa.String(length=100)),
        sa.column("python_field", sa.String(length=200)),
        sa.column("is_insert", sa.Boolean()),
        sa.column("is_edit", sa.Boolean()),
        sa.column("is_list", sa.Boolean()),
        sa.column("is_query", sa.Boolean()),
        sa.column("query_type", sa.String(length=50)),
        sa.column("html_type", sa.String(length=100)),
        sa.column("dict_type", sa.String(length=200)),
        sa.column("sort", sa.Integer()),
        sa.column("status", sa.Integer()),
        sa.column("description", sa.Text()),
        sa.column("uuid", sa.String(length=64)),
        sa.column("is_deleted", sa.Boolean()),
        sa.column("created_time", sa.DateTime(timezone=True)),
        sa.column("updated_time", sa.DateTime(timezone=True)),
        sa.column("deleted_time", sa.DateTime(timezone=True)),
    )


def _ensure_generator_metadata(bind) -> None:
    table_names = set(sa.inspect(bind).get_table_names())
    if not {"gen_table", "gen_table_column"}.issubset(table_names):
        return

    gen_table = _generator_table()
    table_id = bind.execute(
        sa.select(gen_table.c.id)
        .where(gen_table.c.table_name == "app_user_kyc", gen_table.c.is_deleted.is_(False))
        .order_by(gen_table.c.id.asc())
        .limit(1)
    ).scalar_one_or_none()
    if table_id is None:
        return

    gen_column = _generator_column_table()
    now = datetime.now(UTC)
    for column_name, config in _GENERATOR_COLUMNS:
        values = {
            "column_name": column_name,
            **config,
            "table_id": table_id,
            "status": 0,
            "is_deleted": False,
            "deleted_time": None,
            "updated_time": now,
        }
        column_id = bind.execute(
            sa.select(gen_column.c.id)
            .where(gen_column.c.table_id == table_id, gen_column.c.column_name == column_name)
            .order_by(gen_column.c.id.asc())
            .limit(1)
        ).scalar_one_or_none()
        if column_id is None:
            bind.execute(
                gen_column.insert().values(
                    **values,
                    uuid=str(uuid4()),
                    created_time=now,
                )
            )
        else:
            bind.execute(gen_column.update().where(gen_column.c.id == column_id).values(**values))


def upgrade() -> None:
    _ensure_generator_metadata(op.get_bind())


def downgrade() -> None:
    # Generator metadata is shared and user-editable; preserve it on downgrade.
    return None
